language: generic

sudo: required

services:
        - docker

before_install:
        - docker build -f Dockerfile.dev -t travisdev .

script:
        - docker run -e CI=true travisdev  npm run test

